name: Publish And Deploy Demo
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:

    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf realworld-nuxtjs
          mkdir realworld-nuxtjs
          cd realworld-nuxtjs  
          wget https://dl0.serctl.com/downloads5/2021-01-27-23-28-29-download-release.tgz -O release.tgz
          tar zxvf release.tgz
          npm ci
          pm2 start
